version: "3.0"

services:
  chromedriver:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"

  bot:
    build: .
#    container_name: tg_bot
    command: python main.py
    volumes:
      - .:/code
    ports:
      - 5433:5432
    links:
      - chromedriver
